version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/gabstv/go-app
    steps:
      - checkout
      - run: go mod download
      - run: go vet ./...
      - run: go test -v -race ./...
